### ISSUE TITLE
Latest Fire TV network does not directly list IP address

### ISSUE THREAD

**Issue by rps700** [amzn/appstore-alexa-docs#19]
I was trying to connect to Fire TV via ADB. I followed steps listed in https://developer.amazon.com/public/solutions/devices/fire-tv/docs/connecting-adb-to-fire-tv-device#networkconnect. However, settings-->network option only lists Wi-Fi name and not IP address. Since, each device in the house gets it's own IP address, even with my Mac is on the same network, it's not very straightforward to find out device specific IP address. I had to visit my internet provider's page to figure out IP address my Fire TV was using. 

It would be great if this document can provide guidance to developers to find IP address of newer versions of Fire TV. Thanks.

**Comment by tomjoht** [comment]
rps700, thanks for noting the issue you experienced. This helps us be more thorough in the docs. However, I am not sure how to replicate the issue you described. When I go to **Settings > Device > About > Network** on both Fire TV Stick Gen 2 and Fire TV box, I see an IP address. Here's a screenshot: https://www.screencast.com/t/RKKuPBbuRx7x. 

What version of Fire TV device are you using? Did you get the latest software update (Settings > Devivce > About > Check for System Update)? Are you saying that you're looking at the same screen as the screenshot I sent, but there's no IP address, just a network name? If so, is that a feature of your particular Internet provider?

**Comment by rps700** [comment]
Hi @tomjoht, 

I have the latest Fire TV https://www.amazon.com/Amazon-Fire-TV-Streaming-Media-Player/dp/B00U3FPN4U/ref=sr_1_1?ie=UTF8&qid=1498257299&sr=8-1&keywords=fire+TV

Please find attached screen shot of the network settings screen. On this particular screen, there is only wi-fi name reference.   
<img width="1096" alt="screen shot 2017-06-23 at 6 36 01 pm" src="https://user-images.githubusercontent.com/1050636/27502576-00212634-5843-11e7-8f24-83f1751654d8.png">

Hope this helps.Thanks.

**Comment by tomjoht** [comment]
Thanks for taking a screenshot. There's *another* Network page on the **Settings** menu. From Settings, go to **Device > About > Network**. You're on **Settings > Network**. The duplicate names are confusing, I know. Anyway, I'm confident you'll see your IP address there.

**Comment by tomjoht** [comment]
I can see how the docs are confusing here. I updated them a bit to try to clarify that there are 2 network screens, and hopefully point users to the right one.
